/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sevvalbilginmainclass;


import javax.swing.JOptionPane;


/**
 *
 * @author hp
 */
public class SevvalBilginGameFrame extends javax.swing.JFrame {

    SevvalBilginCard<Integer> first_card = new SevvalBilginCard<>();
    SevvalBilginCard<Integer> sec_card = new SevvalBilginCard<>();

    public SevvalBilginGameFrame() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(true);

    }

    public SevvalBilginGameFrame(SevvalBilginCard first_card, SevvalBilginCard secCard) {
        initComponents();

        if (isCardsCompletelySame(first_card, secCard)) {
            System.out.println("Cards shouldn't be exactly same so we changed first card!");
            this.first_card = SevvalBilginMainClass.generateCard();
        }
        this.first_card = first_card;
        this.sec_card = secCard;
        System.out.println("First User:");
        first_card.printCard();
        System.out.println("Second User:");
        secCard.printCard();
        System.out.println("-----------------------------------------------------------");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        panel_pink = new javax.swing.JPanel();
        button_select_num = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(255, 204, 204));
        rootPanel.setLayout(new java.awt.GridLayout(1, 0));

        panel_pink.setBackground(new java.awt.Color(255, 204, 204));

        button_select_num.setText("Get Random Number!");
        button_select_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_select_numActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_pinkLayout = new javax.swing.GroupLayout(panel_pink);
        panel_pink.setLayout(panel_pinkLayout);
        panel_pinkLayout.setHorizontalGroup(
            panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pinkLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(button_select_num, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        panel_pinkLayout.setVerticalGroup(
            panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pinkLayout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(button_select_num, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        rootPanel.add(panel_pink);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void checkNum(SevvalBilginCard card, int data) {
        if (first_card.head == card.head) {
            System.out.println("First User:");

        } else {
            System.out.println("Second User:");

        }
        SevvalBilginNode<Integer> row_temp = card.head;
        SevvalBilginNode<Integer> col_temp = card.head;
        boolean is_same_row = true;
        while (row_temp != null) {
            col_temp = row_temp;
            while (col_temp != null) {

                if (col_temp.data == data) {
                    col_temp.sign = SevvalBilginNode.Sign.minus;

                    is_same_row = checkRow(col_temp);
                    if (is_same_row) {
                        card.bingo_counter++;
                    }
                    if (card.bingo_counter == 1 && is_same_row) {
                        System.out.println("First Bingo!");
                    } else if (card.bingo_counter == 2 && card.bingo_counter < 15 && is_same_row) {

                        System.out.println("Second Bingo!");
                    } else if (card.bingo_counter == 3 && is_same_row) {

                        System.out.println("Last Bingo! and game Finished!Winner's card:");
                        card.printCard();
                        System.exit(0);
                    }

                    break;
                }

                col_temp = col_temp.next;

            }

            row_temp = row_temp.down;
        }

        card.printCard();
        
    }

    public boolean checkRow(SevvalBilginNode node) {

        while (node.prev != null) {
            node = node.prev;

        }
        while (node != null) {

            if (node.sign == SevvalBilginNode.Sign.plus) {
                return false;
            }
            node = node.next;
        }

        return true;
    }

    static int counter = 0;

    private void button_select_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_select_numActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(rootPane, "Number is: " + SevvalBilginMainClass.arr[counter]);
        
        checkNum(first_card, SevvalBilginMainClass.arr[counter]);
        checkNum(sec_card, SevvalBilginMainClass.arr[counter]);

        System.out.println("-------------------------------------------------");
        counter++;


    }//GEN-LAST:event_button_select_numActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_select_num;
    private javax.swing.JPanel panel_pink;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables

    private boolean isCardsCompletelySame(SevvalBilginCard first_card, SevvalBilginCard secCard) {
        SevvalBilginNode<Integer> first_row_temp = first_card.head;
        SevvalBilginNode<Integer> first_col_temp = first_card.head;
        SevvalBilginNode<Integer> sec_row_temp = secCard.head;
        SevvalBilginNode<Integer> sec_col_temp = secCard.head;
        while (first_row_temp != null && sec_row_temp != null) {
            while (first_col_temp != null && sec_col_temp != null) {
                if (first_col_temp.data != sec_col_temp.data) {
                    return false;
                }
                first_col_temp = first_col_temp.next;
                sec_col_temp = sec_col_temp.next;
            }
            first_row_temp = first_row_temp.down;
            sec_row_temp = sec_row_temp.down;
        }

        return true;
    }
}
